# Generated by Django 4.1.7 on 2023-03-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=12)),
            ],
        ),
    ]
