# Generated by Django 4.1.7 on 2023-03-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('Preco', models.FloatField()),
                ('Cod_servico', models.IntegerField()),
                ('Cod_Produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cartao', models.IntegerField()),
                ('bandeira', models.CharField(max_length=30)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cartao',
            constraint=models.UniqueConstraint(fields=('n_cartao', 'idCliente'), name='unique_ncartao_idcliente_combination'),
        ),
    ]
