# Generated by Django 4.1.7 on 2023-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pedido_cartao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=300)),
                ('cnpj', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
