# Generated by Django 4.1.7 on 2023-03-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recebepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_pagamento', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
