# Generated by Django 4.1.7 on 2023-03-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pagamento')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
            options={
                'unique_together': {('idCliente', 'idPedido')},
            },
        ),
    ]
