# Generated by Django 4.1.7 on 2023-03-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fazpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especieDest', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('duracao', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
    ]
