# Generated by Django 4.1.7 on 2023-03-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vendeproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfereceServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cd_Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('Cod_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
            ],
        ),
    ]
