# Generated by Django 4.1.7 on 2023-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_ofereceservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
